name = "Syndikat Expansion";
author = "ScottyThePilot";
logoSmall = "\sct\syndikat_expansion\addons\main\data\logo_small.paa";
logo = "\sct\syndikat_expansion\addons\main\data\logo.paa";
logoOver = "\sct\syndikat_expansion\addons\main\data\logo.paa";
dlcColor[] = { 0.88, 0.88, 0.88, 1 };
overview = "Gives Syndikat some extra equipment for use in mission-making.";
hideName = 0;
hidePicture = 0;
