name = "Syndikat Expansion"
author = "ScottyThePilot"
prefix = "syndikat_expansion"
mainprefix = "sct"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
  "mod.cpp",
  "README",
  "README.md",
  "LICENSE"
]
exclude = [
  "**/*.hpp",
  "**/*.psd",
  "**/*.xz"
]

[hemtt.release]
sign = true
archive = false
