name = "Syndikat Expansion"
author = "ScottyThePilot"
prefix = "syndikat_expansion"
mainprefix = "sct"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
exclude = [
  "**/*.hpp"
]
